#pragma once

//Include this file to use Oxygen
#include "Base/KeyCodes.h"
#include "Base/MouseButtonCodes.h"
#include "Base/Base.h"
#include "GameWindow/GameWindow.h"
#include "Events/EventManager.h"
#include "Input/Input.h"
#include "Renderer/Renderer.h"
#include "Renderer/Renderer2D.h"
#include "Renderer/VertexArray.h"
#include "Renderer/Buffer.h"
#include "Renderer/Shader.h"
#include "Renderer/Framebuffer.h"
#include "Renderer/Texture2D.h"
#include "Renderer/SubTexture2D.h"
#include "Renderer/OrthographicCameraController.h"
#include "Renderer/OrthographicCamera.h"
#include "ECS/Scene/Scene.h"
#include "ECS/Components/Components.h"
#include "ECS/GameObject/GameObject.h"
#include "ParticleSystem/ParticleSystem.h"
#include "Math/Math.h"
#include "Debug/Debug.h"
#include "Random/Random.h"
#include "Time/Time.h"
#include "ImGui/ImGuiLayer.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>