#pragma once

#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <map>

#define GLFW_MOUSEBUTTON_COUNT 12

#define OX_MOUSEBUTTON_1         0
#define OX_MOUSEBUTTON_2         1
#define OX_MOUSEBUTTON_3         2
#define OX_MOUSEBUTTON_4         3
#define OX_MOUSEBUTTON_5         4
#define OX_MOUSEBUTTON_6         5
#define OX_MOUSEBUTTON_7         6
#define OX_MOUSEBUTTON_8         7
#define OX_MOUSEBUTTON_LAST      OX_MOUSEBUTTON_8
#define OX_MOUSEBUTTON_LEFT      OX_MOUSEBUTTON_1
#define OX_MOUSEBUTTON_RIGHT     OX_MOUSEBUTTON_2
#define OX_MOUSEBUTTON_MIDDLE    OX_MOUSEBUTTON_3

const std::map<int, int> MOUSEBUTTON_DEFINITIONS
{
	{ GLFW_MOUSE_BUTTON_1,		  OX_MOUSEBUTTON_1 },
	{ GLFW_MOUSE_BUTTON_2,		  OX_MOUSEBUTTON_2 },
	{ GLFW_MOUSE_BUTTON_3,		  OX_MOUSEBUTTON_3 },
	{ GLFW_MOUSE_BUTTON_4,		  OX_MOUSEBUTTON_4 },
	{ GLFW_MOUSE_BUTTON_5,		  OX_MOUSEBUTTON_5 },
	{ GLFW_MOUSE_BUTTON_6,		  OX_MOUSEBUTTON_6 },
	{ GLFW_MOUSE_BUTTON_7,		  OX_MOUSEBUTTON_7 },
	{ GLFW_MOUSE_BUTTON_8,		  OX_MOUSEBUTTON_8 },
	{ GLFW_MOUSE_BUTTON_LAST,	  OX_MOUSEBUTTON_LAST },
	{ GLFW_MOUSE_BUTTON_LEFT,	  OX_MOUSEBUTTON_LEFT },
	{ GLFW_MOUSE_BUTTON_RIGHT,    OX_MOUSEBUTTON_RIGHT },
	{ GLFW_MOUSE_BUTTON_MIDDLE,   OX_MOUSEBUTTON_MIDDLE }
};